package kirin.core;

import kirin.core.context.ApplicationContext;
import kirin.core.factory.BeanFactory;

public class Application {
    public static ApplicationContext applicationContext;

    /**
     * The main method for starting the formation of the kirin context
     * @return the application context generated by the project settings
     */
    public static ApplicationContext run() {
        applicationContext = new ApplicationContext();
        BeanFactory beanFactory = new BeanFactory(applicationContext);
        applicationContext.setBeanFactory(beanFactory);
        applicationContext.createBeanContext();
        return applicationContext;
    }
}
